### ISSUE TITLE
Documentation is out-of-date

### ISSUE THREAD

**Issue by kohesion** [victorvoid/placeload.js#13]
Various aspects of documentation seem to be out-of-date.

Most frustrating of all, the sample code doesn't work. 

A jsfiddle or codepen would be helpful.

**Comment by victorvoid** [comment]
I'll create a documentation with examples, thanks for you feedback, I'll use Jsfiddle to examples. The examples in README.md is the 1.0.0 version, sorry in don't published the new version@1.0.0 but now is available.
