### ISSUE TITLE
Stays always visible and don't mask the content

### ISSUE THREAD

**Issue by ANONIMNIQ** [victorvoid/placeload.js#16]
I'm not sure what I'm doing wrong. I add placeload and use the code from the example, trying to integrate it in my wordpress site. Placeholder always stays visible above the content, don't mask anything and never disappear.

**Comment by victorvoid** [comment]
You should use the placeload when you need to make a call to get the content, and remove when the call ends. You can use the `.remove()` to remove the loader. 

See if it will help you:

```js
const userLoader = Placeload
    .$('.user-placeload')
    .config({speed: '2s'})
    .line((element) => element.width(300).height(200))
    .config({spaceBetween: '30px'})
    .line((element) => element.width(400).height(20))
    .config({spaceBetween: '30px'})
    .line((element) => element.width(400).height(20))
    .config({spaceBetween: '30px'})
    .line((element) => element.width(250).height(20))


userLoader.fold(
  (err) => console.log('error: ', err),
  (allElements) => console.log('allElements: ', allElements)
)

API.getUsers()
  .then(users => {
      userLoader.remove() //<--- HERE YOU ARE REMOVING THE LOAD
    }
  )
```

**Comment by ANONIMNIQ** [comment]
Thank you! Can you explain me this part of the code, please!
`API.getUsers()
  .then(users => {
      userLoader.remove() //<--- HERE YOU ARE REMOVING THE LOAD
    }
  )`
I'm not sure about getUsers() part of the code. Did I need to replace It with something else?

**Comment by ANONIMNIQ** [comment]
This code from the example works


```
<script>
--
  | const user = Placeload
  | .$('.user-placeload')
  | .config({speed: '2s'})
  | .line((element) => element.width(300).height(200))
  | .config({spaceBetween: '10px'})
  | .line((element) => element.width(100).height(20))
  | .config({spaceBetween: '10px', right: true})
  | .line((element) => element.width(50).height(20))
  | .fold(
  | (err) => console.log('error: ', err),
  | (allElements) => console.log('allElements: ', allElements)
  | )
  | // simulation API
  | setTimeout(() => {
  | user.remove()
  | }, 2000)
  | </script>
```

Now the only problem is that the placeload is above the content and didn't mask it when load. Even in the example index.html this is the same.
In vanillajs example content is masked with css, I want the same thing but without the toggle - just placeload with hidden content when preloading and after that content to be visible.

**Comment by victorvoid** [comment]
I do not know if I understand your problem, but it seems that you want the placeload to know when its content is loaded, it disappears automatically, but it can not identify it, so you need to use the `.remove` property, so it can be removed. So it's good for SPA, because they use [AJAX](https://developer.mozilla.org/en-US/docs/AJAX/Getting_Started) calls to load their content, if you is not using AJAX, the placeload will not be good for you :/
