### ISSUE TITLE
Reload the placeload

### ISSUE THREAD

**Issue by zapping** [victorvoid/placeload.js#17]
Nice library!!! If I have a 'Refresh Data' button on my page how can the placeload be shown when the button is clicked. Is a function similar to remove() that loads the placeload elements?

**Comment by victorvoid** [comment]
Thanks for you feedback! 

Yes, you can use the `.fold` when the button is clicked, for example: 

```js

//painting the loader
const userLoader = Placeload
  .$('.user-placeload')
  .config({speed: '2s'})
  .line((element) => element.width(100).height(50))

const btn = document.querySelector('.btn-load')

btn.addEventListener('click', () =>  {
  //running
  userLoader.fold(
    (err) => console.log('error: ', err),
    (allElements) => console.log('allElements: ', allElements)
  )
})
```
Placeload uses lazy evaluation, in that nothing is evaluated until necessary, so use the function `.fold()`

`.fold params:`
`1º param: function to catch the error.`
`2º param: function is running when to paint successfully. `

Maybe It can help you.

**Comment by zapping** [comment]
Thank you!!!.
