### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by rosostolato** [victorvoid/placeload.js#19]
I'm importing with webpack and these both ways are not working:
```
import Placeload from 'placeload.js'

const userLoader = Placeload
  .$('.user-placeload')
```
```
import Placeload from 'placeload.js'

const userLoader = new Placeload('.user-placeload')
```

I tried to print Placeload to console and it's importing an empty object

**Comment by victorvoid** [comment]
thanks for reporting, fixed in 1.0.4 version. :smiley:
