### ISSUE TITLE
Remove drawing... in the browser console

### ISSUE THREAD

**Issue by LeCoupa** [victorvoid/placeload.js#5]
Hey! Thanks a lot for your package! :)

I would like to know how I can remove "drawing..." in the console. Is there a way? I am not sure it is really useful.

**Comment by victorvoid** [comment]
Thanks! sorry, log removed! :D

**Comment by LeCoupa** [comment]
Thanks :) I think you should also update the version number of your package (https://github.com/victorvoid/placeload.js/blob/master/package.json).

That way, we can run `npm update` and it should take changes into account. :)
https://docs.npmjs.com/cli/update
